version: "3.8"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: weather_api
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "9000:9000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: weather_api
      ENVIRONMENT: local
      SERVICE_PORT: 9000
      SERVICE_DATABASE_TABLE: weather
      API_KEY: 4d1e87732e94ffd1804af4941ec7b355
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: